# Module 6 Challenge - Part 2

In [1]:
%matplotlib inline
%matplotlib notebook
# Import the dependencies.
import pandas as pd
import gmaps
import requests
import numpy as np
# Import the API key.
from config import g_key

In [2]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

Weather_df = pd.read_csv("Data/WeatherPy_challenge.csv")
Weather_df

,Unnamed: 0,City,Country,Date,Lat,Lng,Max Temp,Humidity %,Cloudiness %,Wind Speed (mph),Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
0,0,Bonavista,CA,2020-02-21 01:11:12,48.65,-53.11,9.00,65,94,23.00,overcast clouds,0.00,0.0
1,1,Kavieng,PG,2020-02-21 01:11:13,-2.57,150.80,83.57,74,47,9.69,scattered clouds,0.00,0.0
2,2,Cape Town,ZA,2020-02-21 01:08:06,-33.93,18.42,66.00,88,0,16.11,clear sky,0.00,0.0
3,3,Mecca,SA,2020-02-21 01:10:15,21.43,39.83,60.39,46,0,2.95,clear sky,0.00,0.0
4,4,Ushuaia,AR,2020-02-21 01:11:13,-54.80,-68.30,51.80,66,75,6.04,broken clouds,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
542,542,Discovery Bay,US,2020-02-21 01:13:12,37.91,-121.60,68.00,42,1,9.17,clear sky,0.00,0.0
543,543,Creel,MX,2020-02-21 01:13:12,27.75,-107.63,64.69,44,0,7.96,clear sky,0.00,0.0
544,544,Sambava,MG,2020-02-21 01:13:12,-14.27,50.17,72.23,98,100,1.70,light rain,0.13,0.0
545,545,Hammond,US,2020-02-21 01:13:12,41.58,-87.50,21.00,61,5,3.67,clear sky,0.00,0.0
546,546,Axim,GH,2020-02-21 01:13:13,4.87,-2.24,78.80,90,79,3.18,broken clouds,0.00,0.0

In [3]:
##### Ask the customer for preferences (minimum and maximum temperatures, snow and/or rain fall)
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))
yesno_snow = input("Do you want it to be snowing? ")
yesno_rain = input("Do you want it to be raining? ")

What is the minimum temperature you would like for your trip? 55
What is the maximum temperature you would like for your trip? 75
Do you want it to be snowing? no
Do you want it to be raining? no

In [4]:
# Filter the dataset to find the cities that fit the criteria.
#min_temp = 75
#max_temp = 90

if (yesno_rain.lower() == "yes") & (yesno_snow.lower() == "yes"):
    preferred_cities_df = Weather_df.loc[(Weather_df["Max Temp"] <= max_temp) & \
                                       (Weather_df["Max Temp"] >= min_temp) & \
                                        (Weather_df["Snow inches (last 3 hrs)"] > 0) & \
                                        (Weather_df["Rain inches (last 3 hrs)"] > 0)]
elif (yesno_rain.lower() == "yes") & (yesno_snow.lower() == "no"):
    preferred_cities_df = Weather_df.loc[(Weather_df["Max Temp"] <= max_temp) & \
                                       (Weather_df["Max Temp"] >= min_temp) & \
                                        (Weather_df["Snow inches (last 3 hrs)"] == 0) & \
                                        (Weather_df["Rain inches (last 3 hrs)"] > 0)]
elif (yesno_rain.lower() == "no") & (yesno_snow.lower() == "yes"):
    preferred_cities_df = Weather_df.loc[(Weather_df["Max Temp"] <= max_temp) & \
                                       (Weather_df["Max Temp"] >= min_temp) & \
                                        (Weather_df["Snow inches (last 3 hrs)"] > 0) & \
                                        (Weather_df["Rain inches (last 3 hrs)"] == 0)]
else:
    preferred_cities_df = Weather_df.loc[(Weather_df["Max Temp"] <= max_temp) & \
                                       (Weather_df["Max Temp"] >= min_temp) & \
                                        (Weather_df["Snow inches (last 3 hrs)"] == 0) & \
                                        (Weather_df["Rain inches (last 3 hrs)"] == 0)]
preferred_cities_df.head(10)

,Unnamed: 0,City,Country,Date,Lat,Lng,Max Temp,Humidity %,Cloudiness %,Wind Speed (mph),Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
2,2,Cape Town,ZA,2020-02-21 01:08:06,-33.93,18.42,66.00,88,0,16.11,clear sky,0.0,0.0
3,3,Mecca,SA,2020-02-21 01:10:15,21.43,39.83,60.39,46,0,2.95,clear sky,0.0,0.0
10,10,Punta Arenas,CL,2020-02-21 01:11:15,-53.15,-70.92,55.40,66,75,11.41,broken clouds,0.0,0.0
27,27,Camana,PE,2020-02-21 01:11:18,-16.62,-72.71,69.30,81,70,4.99,broken clouds,0.0,0.0
33,33,Bredasdorp,ZA,2020-02-21 01:11:20,-34.53,20.04,63.00,87,22,2.24,few clouds,0.0,0.0
34,34,Atar,MR,2020-02-21 01:11:20,20.52,-13.05,71.51,13,0,8.68,clear sky,0.0,0.0
41,41,Banda Aceh,ID,2020-02-21 01:11:22,5.56,95.32,72.41,86,26,5.70,scattered clouds,0.0,0.0
48,48,Gilbues,BR,2020-02-21 01:11:23,-9.83,-45.34,69.31,81,74,3.44,broken clouds,0.0,0.0
49,49,East London,ZA,2020-02-21 01:11:23,-33.02,27.91,74.05,77,61,7.65,broken clouds,0.0,0.0
53,53,Hobart,AU,2020-02-21 01:10:28,-42.88,147.33,62.01,41,75,16.11,light intensity shower rain,0.0,0.0

In [5]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description","Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Cape Town,ZA,66.00,clear sky,-33.93,18.42,
3,Mecca,SA,60.39,clear sky,21.43,39.83,
10,Punta Arenas,CL,55.40,broken clouds,-53.15,-70.92,
27,Camana,PE,69.30,broken clouds,-16.62,-72.71,
33,Bredasdorp,ZA,63.00,few clouds,-34.53,20.04,
34,Atar,MR,71.51,clear sky,20.52,-13.05,
41,Banda Aceh,ID,72.41,scattered clouds,5.56,95.32,
48,Gilbues,BR,69.31,broken clouds,-9.83,-45.34,
49,East London,ZA,74.05,broken clouds,-33.02,27.91,
53,Hobart,AU,62.01,light intensity shower rain,-42.88,147.33,

In [6]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [7]:

# Display pop up format template
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} Â°F</dd>
</dl>
"""

hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [8]:
# Add a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
file_name = "Data/WeatherPy_vacation.csv"
hotel_df.to_csv(file_name)
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Cape Town,ZA,66.00,clear sky,-33.93,18.42,Southern Sun Waterfront Cape Town
3,Mecca,SA,60.39,clear sky,21.43,39.83,Hotel Fairmont Makkah Clock Royal Tower
10,Punta Arenas,CL,55.40,broken clouds,-53.15,-70.92,Hotel Dreams Del Estrecho
27,Camana,PE,69.30,broken clouds,-16.62,-72.71,Hostal Morales
33,Bredasdorp,ZA,63.00,few clouds,-34.53,20.04,Bredasdorp Country Manor
...,...,...,...,...,...,...,...
532,Capao Da Canoa,BR,73.18,scattered clouds,-29.75,-50.01,Hotel AraÃ§Ã¡
537,Luangwa,ZM,71.29,broken clouds,-15.62,30.42,Gerasimos Safari Lodge
539,Goure,NE,70.00,clear sky,13.98,10.27,
542,Discovery Bay,US,68.00,clear sky,37.91,-121.60,Orwood Resort Inc
543,Creel,MX,64.69,clear sky,27.75,-107.63,Best Western Plus The Lodge at Creel