# Module 6 Challenge - Part 2

In [1]:
%matplotlib inline
%matplotlib notebook
# Import the dependencies.
import pandas as pd
import gmaps
import requests
import numpy as np
# Import the API key.
from config import g_key

In [2]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

Weather_df = pd.read_csv("WeatherPy_challenge.csv")
Weather_df

,Unnamed: 0,City,Country,Date,Lat,Lng,Max Temp,Humidity %,Cloudiness %,Wind Speed (mph),Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
0,0,Mataura,NZ,2020-02-20 22:04:12,-46.19,168.86,66.38,74,87,3.87,overcast clouds,0.00,0.00
1,1,Lat Yao,TH,2020-02-20 22:04:12,15.75,99.79,73.20,49,14,5.32,few clouds,0.00,0.00
2,2,Port Elizabeth,ZA,2020-02-20 22:00:05,-33.92,25.57,68.00,88,32,13.87,light rain,0.31,0.00
3,3,Ushuaia,AR,2020-02-20 22:04:12,-54.80,-68.30,53.60,62,90,14.99,light rain,0.00,0.00
4,4,Ourossogui,SN,2020-02-20 22:04:13,15.61,-13.32,77.00,47,51,7.34,broken clouds,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
568,568,Cabedelo,BR,2020-02-20 22:06:11,-6.98,-34.83,77.00,94,90,5.82,overcast clouds,0.00,0.00
569,569,Starobaltachevo,RU,2020-02-20 22:06:11,56.00,55.92,29.44,96,100,8.14,light snow,0.00,0.13
570,570,Nioro,GM,2020-02-20 22:06:12,13.35,-15.75,88.03,8,58,6.89,broken clouds,0.00,0.00
571,571,Valleyview,CA,2020-02-20 22:06:12,55.07,-117.29,35.49,82,33,9.86,scattered clouds,0.00,0.00
572,572,Iracoubo,GF,2020-02-20 22:06:12,5.48,-53.20,78.31,73,100,11.52,overcast clouds,0.00,0.00

In [3]:
##### Ask the customer for preferences (minimum and maximum temperatures, snow and/or rain fall)
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))
yesno_snow = input("Do you want it to be snowing? ")
yesno_rain = input("Do you want it to be raining? ")

What is the minimum temperature you would like for your trip? 55
What is the maximum temperature you would like for your trip? 75
Do you want it to be snowing? no
Do you want it to be raining? no

In [4]:
# Filter the dataset to find the cities that fit the criteria.
#min_temp = 75
#max_temp = 90

if (yesno_rain.lower() == "yes") & (yesno_snow.lower() == "yes"):
    preferred_cities_df = Weather_df.loc[(Weather_df["Max Temp"] <= max_temp) & \
                                       (Weather_df["Max Temp"] >= min_temp) & \
                                        (Weather_df["Snow inches (last 3 hrs)"] > 0) & \
                                        (Weather_df["Rain inches (last 3 hrs)"] > 0)]
elif (yesno_rain.lower() == "yes") & (yesno_snow.lower() == "no"):
    preferred_cities_df = Weather_df.loc[(Weather_df["Max Temp"] <= max_temp) & \
                                       (Weather_df["Max Temp"] >= min_temp) & \
                                        (Weather_df["Snow inches (last 3 hrs)"] == 0) & \
                                        (Weather_df["Rain inches (last 3 hrs)"] > 0)]
elif (yesno_rain.lower() == "no") & (yesno_snow.lower() == "yes"):
    preferred_cities_df = Weather_df.loc[(Weather_df["Max Temp"] <= max_temp) & \
                                       (Weather_df["Max Temp"] >= min_temp) & \
                                        (Weather_df["Snow inches (last 3 hrs)"] > 0) & \
                                        (Weather_df["Rain inches (last 3 hrs)"] == 0)]
else:
    preferred_cities_df = Weather_df.loc[(Weather_df["Max Temp"] <= max_temp) & \
                                       (Weather_df["Max Temp"] >= min_temp) & \
                                        (Weather_df["Snow inches (last 3 hrs)"] == 0) & \
                                        (Weather_df["Rain inches (last 3 hrs)"] == 0)]
preferred_cities_df.head(10)

,Unnamed: 0,City,Country,Date,Lat,Lng,Max Temp,Humidity %,Cloudiness %,Wind Speed (mph),Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
0,0,Mataura,NZ,2020-02-20 22:04:12,-46.19,168.86,66.38,74,87,3.87,overcast clouds,0.0,0.0
1,1,Lat Yao,TH,2020-02-20 22:04:12,15.75,99.79,73.20,49,14,5.32,few clouds,0.0,0.0
10,10,Busselton,AU,2020-02-20 22:04:03,-33.65,115.33,68.00,34,70,15.84,broken clouds,0.0,0.0
11,11,Laguna,US,2020-02-20 22:04:14,38.42,-121.42,69.01,42,1,6.93,clear sky,0.0,0.0
12,12,Hobart,AU,2020-02-20 21:59:42,-42.88,147.33,55.00,50,75,12.75,light intensity shower rain,0.0,0.0
17,17,Geraldton,AU,2020-02-20 22:04:15,-28.77,114.60,73.40,83,99,3.36,overcast clouds,0.0,0.0
18,18,Victoria,HK,2020-02-20 22:01:08,22.29,114.16,62.60,67,0,8.05,clear sky,0.0,0.0
21,21,Bredasdorp,ZA,2020-02-20 22:04:16,-34.53,20.04,62.60,82,7,2.24,clear sky,0.0,0.0
22,22,Marawi,PH,2020-02-20 22:04:16,8.00,124.29,70.00,82,0,7.00,clear sky,0.0,0.0
42,42,Chuy,UY,2020-02-20 22:04:20,-33.70,-53.46,68.29,47,6,16.96,clear sky,0.0,0.0

In [5]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description","Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Mataura,NZ,66.38,overcast clouds,-46.19,168.86,
1,Lat Yao,TH,73.20,few clouds,15.75,99.79,
10,Busselton,AU,68.00,broken clouds,-33.65,115.33,
11,Laguna,US,69.01,clear sky,38.42,-121.42,
12,Hobart,AU,55.00,light intensity shower rain,-42.88,147.33,
17,Geraldton,AU,73.40,overcast clouds,-28.77,114.60,
18,Victoria,HK,62.60,clear sky,22.29,114.16,
21,Bredasdorp,ZA,62.60,clear sky,-34.53,20.04,
22,Marawi,PH,70.00,clear sky,8.00,124.29,
42,Chuy,UY,68.29,clear sky,-33.70,-53.46,

In [6]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [7]:

# Display pop up format template
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [8]:
# Add a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
file_name = "WeatherPy_vacation.csv"
hotel_df.to_csv(file_name)
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Mataura,NZ,66.38,overcast clouds,-46.19,168.86,Ellie's Villa
1,Lat Yao,TH,73.20,few clouds,15.75,99.79,ห้างหุ้นส่วนจำกัด ลาดยาวการเกษตร
10,Busselton,AU,68.00,broken clouds,-33.65,115.33,Observatory Guest House
11,Laguna,US,69.01,clear sky,38.42,-121.42,Holiday Inn Express & Suites Elk Grove Ctrl - ...
12,Hobart,AU,55.00,light intensity shower rain,-42.88,147.33,St Ives Apartments
...,...,...,...,...,...,...,...
545,Gwanda,ZW,73.02,few clouds,-20.93,29.00,Mafax Homeways
547,Ginir,ET,64.54,scattered clouds,7.13,40.70,Sura Dare Village
557,Madera,US,73.00,clear sky,37.17,-119.83,
563,Qandala,SO,73.85,broken clouds,11.47,49.87,
564,Kapit,MY,71.40,broken clouds,2.02,112.93,Hotel Meligai Kapit